In [2]:
import numpy as np

In [53]:
points = np.arange(12).reshape(3,4)
print(points[0].shape) # degenerate
print(points[0, np.newaxis].shape) # correct

(4,)
(1, 4)


In [27]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
b = np.arange(30).reshape(6,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
# we want 18 distances between rows of (6,5) and (3,5)
# (6,5) could not be broadcased with (3,5)
# (6,5) could be broadcased with (3,1,5) resulting in (3,6,5)
b - a[:, np.newaxis, :]

array([[[  0,   0,   0,   0,   0],
        [  5,   5,   5,   5,   5],
        [ 10,  10,  10,  10,  10],
        [ 15,  15,  15,  15,  15],
        [ 20,  20,  20,  20,  20],
        [ 25,  25,  25,  25,  25]],

       [[ -5,  -5,  -5,  -5,  -5],
        [  0,   0,   0,   0,   0],
        [  5,   5,   5,   5,   5],
        [ 10,  10,  10,  10,  10],
        [ 15,  15,  15,  15,  15],
        [ 20,  20,  20,  20,  20]],

       [[-10, -10, -10, -10, -10],
        [ -5,  -5,  -5,  -5,  -5],
        [  0,   0,   0,   0,   0],
        [  5,   5,   5,   5,   5],
        [ 10,  10,  10,  10,  10],
        [ 15,  15,  15,  15,  15]]])

In [49]:
# (3,5) could be broadcasted with (6,1,5) resulting in (6,3,5)
# gives same 18 distances in a different order.
b[:, np.newaxis, :] - a

array([[[  0,   0,   0,   0,   0],
        [ -5,  -5,  -5,  -5,  -5],
        [-10, -10, -10, -10, -10]],

       [[  5,   5,   5,   5,   5],
        [  0,   0,   0,   0,   0],
        [ -5,  -5,  -5,  -5,  -5]],

       [[ 10,  10,  10,  10,  10],
        [  5,   5,   5,   5,   5],
        [  0,   0,   0,   0,   0]],

       [[ 15,  15,  15,  15,  15],
        [ 10,  10,  10,  10,  10],
        [  5,   5,   5,   5,   5]],

       [[ 20,  20,  20,  20,  20],
        [ 15,  15,  15,  15,  15],
        [ 10,  10,  10,  10,  10]],

       [[ 25,  25,  25,  25,  25],
        [ 20,  20,  20,  20,  20],
        [ 15,  15,  15,  15,  15]]])

In [51]:
dists = np.sum((b - a[:, np.newaxis, :])**2, axis=2)
dists

array([[   0,  125,  500, 1125, 2000, 3125],
       [ 125,    0,  125,  500, 1125, 2000],
       [ 500,  125,    0,  125,  500, 1125]])