In [1]:
from collections import Counter
import numpy as np

### KNN

In [21]:
x_train = np.arange(48).reshape(12,4)
y_train = np.array([2,1,2,2,3,1,2,2,3,1,2,2])
x_test = np.arange(20).reshape(5,4)
y_test = np.array([1,2,2,1,2])

num_train, num_test = x_train.shape[0], x_test.shape[0]

In [18]:
# distance matrix with one for loop
dists = np.zeros((num_test, num_train)) # kernel matrix
for i in range(num_test):
    dists[i,:] = np.linalg.norm(x_train - x_test[i,:], axis=1)
dists

array([[ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72., 80., 88.],
       [ 8.,  0.,  8., 16., 24., 32., 40., 48., 56., 64., 72., 80.],
       [16.,  8.,  0.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [24., 16.,  8.,  0.,  8., 16., 24., 32., 40., 48., 56., 64.],
       [32., 24., 16.,  8.,  0.,  8., 16., 24., 32., 40., 48., 56.]])

In [19]:
# distance matrix without for loop, much faster
term1 = np.tile(np.sum(x_test**2, axis=1, keepdims=True), [1, num_train])
term2 = np.tile(np.sum(x_train**2, axis=1, keepdims=True).T, [num_test, 1])
term3 = -2 * np.dot(x_test, x_train.T)
dists = np.sqrt(term1 + term2 + term3)
dists

array([[ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72., 80., 88.],
       [ 8.,  0.,  8., 16., 24., 32., 40., 48., 56., 64., 72., 80.],
       [16.,  8.,  0.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [24., 16.,  8.,  0.,  8., 16., 24., 32., 40., 48., 56., 64.],
       [32., 24., 16.,  8.,  0.,  8., 16., 24., 32., 40., 48., 56.]])

In [23]:
K = 3 # num neareset neighbors
y_pred = np.zeros(num_test)
for i in range(num_test):
    inds = np.argsort(dists[i,:])[:K]
    y_pred[i] = sorted(Counter(y_train[inds]).items(), key=lambda x: x[1], reverse=True)[0][0]
y_pred, y_test

(array([2., 2., 2., 2., 3.]), array([1, 2, 2, 1, 2]))

In [26]:
accuracy = sum(y_pred==y_test)/num_test
accuracy

0.4