In [2]:
from collections import Counter
import numpy as np

### slicing

In [336]:
arr = np.arange(24).reshape((2,3,4))
print(arr) # if shape=(x,y,z), there are x arrays of size (y,z)
print("")

# slicing a:b, inclusive for a, not inclusive for b. similar to python list
print(arr[0])
print("")
print(arr[0, 1:3, :])
print("")
print(arr[1, 1:3, 1:4])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 4  5  6  7]
 [ 8  9 10 11]]

[[17 18 19]
 [21 22 23]]


In [319]:
x = np.arange(576).reshape(12,4,4,3)
print(x.shape)

y = np.array([7]*4+[8]*4+[9]*4)
np.random.shuffle(y)
print(y.shape)

# sample 2 instances from each of 3 classes.
n, C = 2, 3
samples = np.zeros([n*C] + list(x.shape[1:]))
for i, lbl in enumerate(set(y)):
    inds = np.where(y==lbl)[0]
    picks = np.random.choice(inds, n)
    samples[i*n:(i+1)*n,:,:,:] = x[picks]
samples.shape

(12, 4, 4, 3)
(12,)


(6, 4, 4, 3)

### stacking

In [334]:
a = np.arange(0,6).reshape(2,3)
b = np.arange(6,15).reshape(3,3)
print(np.vstack([a,b]))
print("")
a = np.arange(0,6).reshape(2,3)
c = np.arange(6,16).reshape(2,5)
print(np.hstack([a,c]))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[[ 0  1  2  6  7  8  9 10]
 [ 3  4  5 11 12 13 14 15]]


### operations

In [77]:
x = np.array([1,3,5,7,9])
y = np.array([2,3,4,5,6])
np.linalg.norm(x-y), np.linalg.norm([3,4])

(3.872983346207417, 5.0)

In [198]:
x = np.array([[1,3,5,6], [2,3,4,5], [0,1,0,2]])
print(x)
print("")
row_sums = np.sum(x, axis=0, keepdims=True); print(row_sums)
print("")
col_sums = np.sum(x, axis=1, keepdims=True); print(col_sums)

[[1 3 5 6]
 [2 3 4 5]
 [0 1 0 2]]

[[ 3  7  9 13]]

[[15]
 [14]
 [ 3]]


In [148]:
# matrix multiplication
a = np.array([[1,2],[4,5],[6,7]]); print(a.shape)
b = np.array([[2,3,4,5],[4,5,6,7]]); print(b.shape)
c = np.dot(a, b); print(c.shape)

(3, 2)
(2, 4)
(3, 4)


In [350]:
# elementwise multiplication
a = np.array([[1,2],[4,5],[6,7]]); print(a.shape)
b = np.array([[2,3],[6,7],[8,9]]); print(b.shape)
c = np.multiply(a, b); print(c.shape) # same as a * b

(3, 2)
(3, 2)
(3, 2)


In [206]:
arr = [2,3,1,4,5]
print(np.argmin(arr))
print(np.argsort(arr))

2
[2 0 1 3 4]


In [269]:
x = np.arange(30).reshape(10,3)
np.array_split(x, 5)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]]),
 array([[24, 25, 26],
        [27, 28, 29]])]

In [268]:
x1 = np.arange(10).reshape(2,5)
x2 = np.arange(10,25).reshape(3,5)
x3 = np.arange(25,30).reshape(1,5)
np.concatenate((x1,x2,x3))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [274]:
x1 = np.arange(6).reshape(3,2)
x2 = np.arange(6,15).reshape(3,3)
np.concatenate((x1,x2), axis=1)

array([[ 0,  1,  6,  7,  8],
       [ 2,  3,  9, 10, 11],
       [ 4,  5, 12, 13, 14]])

In [347]:
arr = np.arange(6).reshape(2,3)
np.tile(arr, [2,2])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [4]:
A = np.array([[3,1,2],[2,0,1],[4,1,1]])  #A = np.array(A)
b = np.array([0,0,1])
x = np.linalg.solve(A,b)

np.linalg.eig(A), #np.rank(A)

((array([ 5.54138127, -1.        , -0.54138127]),
  array([[-6.60372686e-01, -4.47213595e-01,  1.74855890e-01],
         [-3.57513400e-01,  5.96645255e-16, -9.68943154e-01],
         [-6.60372686e-01,  8.94427191e-01,  1.74855890e-01]])),)

### random

In [217]:
np.random.randint(low=0, high=10, size=[3,2,4]) # high is not inclusive.

array([[[4, 7, 3, 7],
        [0, 1, 6, 7]],

       [[8, 8, 4, 1],
        [6, 6, 0, 2]],

       [[8, 0, 1, 9],
        [9, 3, 5, 6]]])

In [234]:
x = np.arange(12).reshape(4,3)
np.random.shuffle(x) # in place shuffle
x

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2]])

In [352]:
x = np.random.normal(scale=2,size=(2,3))
x

array([[ 1.31190107, -2.26962494,  1.72972904],
       [-0.59373042, -1.81327718, -0.01085941]])

In [8]:
np.random.choice(range(5), 3), np.random.choice(range(5), 3, replace=False)

(array([3, 3, 2]), array([1, 4, 2]))

In [9]:
np.linspace(0, 1, 11) # shape (11,)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])