In [1]:
from __future__ import division
from math import log
import random
import numpy as np

log(1), log(8,2)

(0.0, 3.0)

In [4]:
# weighted logistic regression loss imbalanced data
# after applying weights the terms get closer to each other
print(-(log(0.8)+log(0.3)), -(log(0.2)+log(0.7)+log(0.9)+log(0.8)))
print(-0.66*(log(0.8)+log(0.3)), -0.33*(log(0.2)+log(0.7)+log(0.9)+log(0.8)))

1.4271163556401458 2.2946169233448686
0.9418967947224963 0.7572235847038067


### Numpy

In [ ]:
X = np.random.normal(scale=2,size=size)

a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[1,0,-1],[2,0,-1]])

print np.dot(a1,a2.T) # dot product
print np.dot(a2.T,a1) # not commutable
print np.multiply(a1,a2) # element-wise product

In [80]:
arr = np.random.randint(low=0, high=10, size=[4,3,5]) # high is not inclusive.
print(arr)

[[[0 6 1 8 1]
  [4 5 2 0 4]
  [6 4 6 8 7]]

 [[4 0 8 2 1]
  [1 0 2 4 4]
  [9 7 2 1 3]]

 [[0 6 6 3 4]
  [9 1 8 8 5]
  [3 1 1 0 9]]

 [[3 3 9 1 5]
  [2 8 6 4 0]
  [3 1 8 2 8]]]


In [90]:
print(arr[0])
print("")
print(arr[0, 1:3, :])
print("")
print(arr[2, 1:3, 1:4])
print("")
print(arr[2:3, 1:3, 1:4])

[[0 6 1 8 1]
 [4 5 2 0 4]
 [6 4 6 8 7]]

[[4 5 2 0 4]
 [6 4 6 8 7]]

[[1 8 8]
 [1 1 0]]

[[[1 8 8]
  [1 1 0]]]


### Random 

In [67]:
np.random.randint(low=0, high=10, size=4)

array([9, 1, 3, 2])

In [53]:
np.random.choice([2,3,5,1,6,4,2,7,9,8,2], 4)

array([8, 2, 2, 7])

In [12]:
arr = [1,3,5,7,9]
random.shuffle(arr)
arr

[7, 9, 1, 5, 3]

### Hypothesis testing 

In [14]:
from scipy.stats import norm
norm.pdf(-3), norm.pdf(-1), norm.pdf(0), norm.pdf(1), norm.pdf(3)

(0.0044318484119380075,
 0.24197072451914337,
 0.3989422804014327,
 0.24197072451914337,
 0.0044318484119380075)

In [15]:
norm.cdf(-3), norm.cdf(-1), norm.cdf(0), norm.cdf(1), norm.cdf(3)

(0.0013498980316300933,
 0.15865525393145707,
 0.5,
 0.8413447460685429,
 0.9986501019683699)

In [18]:
# inverse of CDF
norm.ppf(0.001349), norm.ppf(0.158655), norm.ppf(0.5), norm.ppf(0.84134), norm.ppf(0.99865)

(-3.0002026930114756,
 -1.000001049431045,
 0.0,
 0.9999803859660787,
 2.9999769927034015)

In [26]:
# alpha-level = 0.05 -> prob = cdf = 0.95 -> z-critical-value = 1.65
norm.ppf(1-0.001), norm.ppf(1-0.01), norm.ppf(1-0.05)
# if z-score=1.9, not significant at pval=0.01, but significant at pval=0.05, since:
# 1.64 < 1.9 < 2.32

(3.090232306167813, 2.3263478740408408, 1.6448536269514722)

In [6]:
[[".",".","4",".",".",".","6","3","."],[".",".",".",".",".",".",".",".","."],["5",".",".",".",".",".",".","9","."],[".",".",".","5","6",".",".",".","."],["4",".","3",".",".",".",".",".","1"],[".",".",".","7",".",".",".",".","."],[".",".",".","5",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."]]

[['.', '.', '4', '.', '.', '.', '6', '3', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['5', '.', '.', '.', '.', '.', '.', '9', '.'],
 ['.', '.', '.', '5', '6', '.', '.', '.', '.'],
 ['4', '.', '3', '.', '.', '.', '.', '.', '1'],
 ['.', '.', '.', '7', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '5', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.']]